# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='variables.Education'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_school',
            field=models.ManyToManyField(blank=True, null=True, to='variables.Education_School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='educational_level',
            field=models.ManyToManyField(blank=True, null=True, to='variables.Educational_Level'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='variables.Region'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
